### ISSUE TITLE
在MIUI14.0.7启动时会因空指针异常闪退

### ISSUE THREAD

**Issue by jerry100129** [Spaso1/FindMaimaiDX_Phone#1]
如题 其余信息暂不了解

**Comment by Spaso1** [comment]
请给出系统版本，安卓版本，闪退错误等具体信息

**Comment by huanli233** [comment]
log呢（

**Comment by jerry100129** [comment]
![QQ图片20241114164515](https://github.com/user-attachments/assets/2c82cc65-d7f4-4de1-8f5f-9ffcec1a5297)
这个是我获得的报错图片
日志我还不知道在哪里搞抱歉（）
系统版本MIUI 14.0.7

**Comment by Spaso1** [comment]
可能是Android15原因？预计今日中午适配

**Comment by Spaso1** [comment]
好像又不是Android15问题，已经可以正常启动

**Comment by Spaso1** [comment]
认为是Android版本原因，请更新到14或者15
