### ISSUE TITLE
Crash when app launches

### ISSUE THREAD

**Issue by I21b** [Spaso1/FindMaimaiDX_Phone#2]
### Describe the bug

Crash every time it starts, even with location permissions and dark mode turned off.

### Expected behavior

App runs normally.

### Steps to reproduce

1. Turn off dark mode
2. Install the app
3. Grant the location permission
4. Open the app and crash

### Device information

Device: Pixel 8 Pro
System: 15 (BP11.241025.006)
Version: 1.000.42r

### Screenshots

![Screenshot_20241118-042631.png](https://github.com/user-attachments/assets/a3f9f918-51ca-4843-8305-f3a4078c2f10)
![Screenshot_20241118-042701.png](https://github.com/user-attachments/assets/fe5e08b4-9a13-4900-989a-0b40b772eb8c)

**Comment by Spaso1** [comment]
Android15还未适配，预计中午完成适配

**Comment by Spaso1** [comment]
现在还存在问题吗，我这边colorOS15 Android15在现版本已经没有报错问题了

**Comment by Spaso1** [comment]
可以把程序崩溃的log写出来吗

**Comment by Spaso1** [comment]
Fixed
